name: haloapp
description: A new Flutter application.

version: 3.0.43+144

environment:
  sdk: ">=2.7.2 <3.0.0"

publish_to: none

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  http: ^0.13.0
  another_flushbar: ^1.12.29
  modal_progress_hud: ^0.1.3
  intl: ^0.17.0
  shared_preferences: ^2.0.5
  # shared_preferences: ^0.4.2
  flutter_google_places: ^0.3.0
  # google_maps_flutter: ^2.0.1
  flutter_polyline_points: ^1.0.0
  # geolocator: ^6.0.0-rc.3
  # geolocator: ^9.0.2
  # firebase_core: ^2.5.0
  # image_picker: ^0.6.7+3
  image_picker: ^0.8.6+1
  # alt_http: ^0.3.0
  # firebase_messaging: ^7.0.3
  # firebase_messaging: ^14.2.2
  # url_launcher: ^5.5.0
  url_launcher: ^6.0.3
  # flutter_local_notifications: ^1.4.4+2
  flutter_local_notifications: ^8.2.0
  # firebase_crashlytics: ^0.1.4+1
  # firebase_crashlytics: ^3.0.0
  flutter_rating_bar: ^4.0.1
  scroll_indicator: ^0.0.3

  package_info: ^2.0.2
  flutter_inappwebview: ^5.1.0+4
  webview_flutter: ^3.0.2
  location_permissions: ^4.0.1
  cached_network_image: ^3.0.0-nullsafety
  flutter_cache_manager: ^3.0.0-nullsafety.1
  image: ^4.0.15
  rxdart: "^0.26.0"
  scroll_to_index: any
  # scroll_to_index:
  #   git:
  #     url: git://github.com/wdjwxh/scroll-to-index.git
  #     ref: master
  # flutter_native_splash: ^1.1.4+1
  huawei_push: ^5.0.2+304
  flutter_hms_gms_availability: ^1.0.0
  huawei_map: ^5.0.3+303
  huawei_site: ^5.1.0+301
  uuid: ^3.0.4
  #  flutter_facebook_login: ^3.0.0
  google_sign_in: ^5.0.5
  sign_in_with_apple: ^4.3.0
  flutter_facebook_auth: ^5.0.7
  pin_code_fields: ^7.3.0
  rect_getter: ^1.0.0
  flutter_staggered_grid_view: ^0.6.2
  carousel_slider: ^4.0.0
  crisp: ^0.3.1
  flutter_share: ^2.0.0
  huawei_hmsavailability: ^6.4.0+303
  uni_links: ^0.5.1
  huawei_location: ^5.1.0+301
  
  # firebase_messaging: ^14.2.2
  # firebase_crashlytics: ^3.0.12
  connectivity_plus: ^3.0.3
  data_connection_checker: ^0.3.4

dependency_overrides:
  flutter_plugin_android_lifecycle: ^2.0.0
  http: ^0.12.2
  flutter_cache_manager: ^3.0.0-nullsafety.1
  rxdart: ^0.26.0
  stream_transform: ^2.0.0
  # firebase_messaging_platform_interface: ^4.2.11
  # firebase_crashlytics_platform_interface: ^3.3.12
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/new/
    - assets/locale/localization_en.json
    - assets/locale/localization_ms.json
    - assets/locale/localization_zh.json
    - assets/configs/consumer_config.json
    - assets/map_style.json

  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: fonts/Poppins/Poppins-Regular.ttf

    - family: Poppins-Black
      fonts:
        - asset: fonts/Poppins/Poppins-Black.ttf

    - family: Poppins-Bold
      fonts:
        - asset: fonts/Poppins/Poppins-Bold.ttf

    - family: Poppins-Light
      fonts:
        - asset: fonts/Poppins/Poppins-Light.ttf

    - family: Poppins-Medium
      fonts:
        - asset: fonts/Poppins/Poppins-Medium.ttf

    - family: Poppins-SemiBold
      fonts:
        - asset: fonts/Poppins/Poppins-SemiBold.ttf

    - family: Poppins-Italic
      fonts:
        - asset: fonts/Poppins/Poppins-Italic.ttf
